### ISSUE TITLE
Steam Half-Life Support

### ISSUE THREAD

**Issue by JS101dotgit** [MaestroFenix/Half-Life-Resized-Maps#11]
Support for Half-Life (Original, Not Source)?

**Comment by MaestroFenix** [comment]
This project is only for Source. Trying to backport this directly on vanilla GoldSrc wouldn't work, as it would hit immediately several BSP limits.

The closest you can get without an engine license to modify the internals, is what Hezus is already doing: https://www.moddb.com/mods/half-life-enriched/

**Comment by JS101dotgit** [comment]
ok thx
